/**
 * 統一エラーコード定義
 */

export const ErrorCodes = {
  // バリデーション
  VALIDATION_REQUIRED: "VALIDATION_REQUIRED",
  VALIDATION_INVALID: "VALIDATION_INVALID",
  VALIDATION_TOO_LONG: "VALIDATION_TOO_LONG",
  VALIDATION_FILE_TOO_LARGE: "VALIDATION_FILE_TOO_LARGE",
  VALIDATION_FILE_TYPE: "VALIDATION_FILE_TYPE",

  // 認証
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",

  // 権限
  FORBIDDEN: "FORBIDDEN",
  SERVER_NOT_ALLOWED: "SERVER_NOT_ALLOWED",

  // リソース
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",

  // レート制限
  RATE_LIMIT: "RATE_LIMIT",

  // タイムアウト
  TIMEOUT_PROCESSING: "TIMEOUT_PROCESSING",
  TIMEOUT_ROTATE: "TIMEOUT_ROTATE",
  TIMEOUT_OVERLAY: "TIMEOUT_OVERLAY",
  TIMEOUT_CONVERT: "TIMEOUT_CONVERT",

  // 内部エラー
  INTERNAL_ERROR: "INTERNAL_ERROR",
  IMAGE_PROCESS_FAILED: "IMAGE_PROCESS_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
